### ISSUE TITLE
Error when using where clause with date string with colon for mysql

### ISSUE THREAD

**Issue by tbantle22** [pihvi/yesql#31]
yesql version 6.1.0

```js
const q = "SELECT * FROM `tablename3` WHERE `dt` < '2023-06-27 03:06:53'"
const { sql, values } = mysql(q)({});
```

```
Error: Missing value for statement.
06 not provided for statement:
SELECT * FROM `tablename3` WHERE `dt` < "2023-06-27 03:06:53"
this was provided:
{}
    at errorMissingValue (/Users/taylor/go/src/github.com/dolthub/ld/hosted-web/node_modules/yesql/yesql.js:107:9)
    at /Users/taylor/go/src/github.com/dolthub/ld/hosted-web/node_modules/yesql/yesql.js:98:18
    at String.replace (<anonymous>)
    at /Users/taylor/go/src/github.com/dolthub/ld/hosted-web/node_modules/yesql/yesql.js:90:18

```

**Comment by pihvi** [comment]
Fixed in version 7.0.0. Can you confirm this works for you?
